### ISSUE TITLE
Is there support to Python3?

### ISSUE THREAD

**Issue by alexandre** [mongolab/dex#30]
I tried install using python 3.4.1:

``` Python
pip install dex
Downloading/unpacking dex
  Downloading Dex-0.6.tar.gz
  Running setup.py (path:...build/dex/setup.py) egg_info for package dex

Requirement already satisfied (use --upgrade to upgrade): pymongo in .../lib/python3.4/site-packages (from dex)
Downloading/unpacking pyyaml (from dex)
  Downloading PyYAML-3.11.tar.gz (248kB): 248kB downloaded
  Running setup.py (path:...build/pyyaml/setup.py) egg_info for package pyyaml

Downloading/unpacking dargparse>=0.2.2 (from dex)
  Downloading dargparse-0.2.5.tar.gz
  Running setup.py (path:..../build/dargparse/setup.py) egg_info for package dargparse
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "..../build/dargparse/setup.py", line 31
        except Exception, ex:
                        ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "..../build/dargparse/setup.py", line 31

    except Exception, ex:

                    ^

SyntaxError: invalid syntax

----------------------------------------

```

[ ]'s

**Comment by PuKoren** [comment]
+1
