### ISSUE TITLE
Error when running pip install dex

### ISSUE THREAD

**Issue by jafetmorales** [mongolab/dex#43]
This is the output when running <code>pip install dex</code>
```
Collecting dex
  Downloading https://files.pythonhosted.org/packages/cd/f4/46dd14cd7787b66f69b02cb5771247eaf6078913a5dccbff0f0ce0825bdb/Dex-0.6.tar.gz
Requirement already satisfied: pymongo in c:\users\jmorales\appdata\roaming\python\python35\site-packages (from dex) (3.3.0)
Requirement already satisfied: pyyaml in c:\users\jmorales\appdata\local\programs\python\python35\lib\site-packages (from dex) (3.11)
Collecting dargparse>=0.2.2 (from dex)
  Downloading https://files.pythonhosted.org/packages/ab/7a/8e6b3985396e164f09f3bb626b52ec2c9b1c88dd9f4dffffd5a2316538d2/dargparse-0.2.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jmorales\AppData\Local\Temp\pip-install-_y0ezmr8\dargparse\setup.py", line 31
        except Exception, ex:
                        ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\jmorales\AppData\Local\Temp\pip-install-_y0ezmr8\dargparse\
```
This is my setup:
>Python version: 3.5
>OS: Windows 10 Home
>System Type: 64-bit Operating System, x64-based processor
>Processor: AMD A10-8700P Radeon R6

**Comment by thawkins** [comment]
I belive dex only runs on python 2.7

**Comment by thawkins** [comment]
The error is discussed here, in python 2.6 and up you should use the keyword 'as' instead of the comma.

https://stackoverflow.com/questions/2535760/python-try-except-comma-vs-as-in-except
